# Generated by Django 3.1.4 on 2021-04-03 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('importance', models.PositiveSmallIntegerField(choices=[(0, 'As an introduction'), (1, 'Learn anytime'), (2, 'Alternative option: pick this or recommended'), (3, 'Recommended')], default=3)),
                ('position_x', models.IntegerField(blank=True, null=True)),
                ('position_y', models.IntegerField(blank=True, null=True)),
                ('previous_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.module')),
            ],
            options={
                'ordering': ('position_y',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('importance', models.PositiveSmallIntegerField(choices=[(0, 'As an introduction'), (1, 'Learn anytime'), (2, 'Alternative option: pick this or recommended'), (3, 'Recommended')], default=3)),
                ('position_x', models.IntegerField(blank=True, null=True)),
                ('position_y', models.IntegerField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='server.module')),
                ('previous_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.topic')),
            ],
            options={
                'ordering': ('position_y',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('importance', models.PositiveSmallIntegerField(choices=[(0, 'As an introduction'), (1, 'Learn anytime'), (2, 'Alternative option: pick this or recommended'), (3, 'Recommended')], default=3)),
                ('position_x', models.IntegerField(blank=True, null=True)),
                ('position_y', models.IntegerField(blank=True, null=True)),
                ('previous_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.subtopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_topics', to='server.topic')),
            ],
            options={
                'ordering': ('position_y',),
                'abstract': False,
            },
        ),
    ]
