# Generated by Django 3.1.4 on 2021-04-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subtopic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
        migrations.RenameField(
            model_name='module',
            old_name='position_x',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='position_y',
            new_name='top',
        ),
        migrations.RenameField(
            model_name='subtopic',
            old_name='position_x',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='subtopic',
            old_name='position_y',
            new_name='top',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='position_x',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='position_y',
            new_name='top',
        ),
    ]
